version: '3.1'
services:
  app:
    container_name: springboot-user
    image: user
    build: ./
    ports:
      - "8811:8811"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user