version: '3.1'
services:
  app:
    container_name: springboot-entity
    image: springboot-entity
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=IoMOB9IVeHuN3FTOhrOL00AcLVGxK1RI
      - POSTGRES_USER=terrain_user
      - POSTGRES_DB=terrain