server:
  port: 8900
spring:
  main:
    web-application-type: reactive  
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
      - id: UserMicroService
        uri: lb://UserMicroService
        predicates:
        - Path=/user/**
      - id: ReservationMicroService
        uri: lb://ReservationMicroService
        predicates:
        - Path=/order/**
      - id: Sportify_entity
        uri: lb://Sportify_entity
        predicates:
        - Path=/terrain/**
eureka:
  client:
    service_url:
      defaultZone : http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false