version: '3.1'
services:
  app:
    container_name: springboot-reservation
    image: reservation
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=reservation