version: '3.1'
services:
  app:
    container_name: eurekaServer
    image: springboot-eureka
    build: ./
    ports:
      - "8761:8761"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      