version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=E3MPD61lcgvffBUt8s06Z06co36JWpru
      - POSTGRES_USER=sportify_terrain_user
      - POSTGRES_DB=sportify_terrain